### ISSUE TITLE
如何向此仓库提交方案？

### ISSUE THREAD

**Issue by laubonghaudoi** [jimmy54/iRime-Resouce#1]
希望能提供一个方案提交指南或守则，方便方案作者直接向此仓库直接提交方案。只要作者允许，我可以将我[收集仓库](https://github.com/laubonghaudoi/Chinese_dialect_Rime_schema)里的完备方案马上提交，令iRime尽快提供多方言支持。

**Comment by jimmy54** [comment]
https://blog.csdn.net/qq1332479771/article/details/56087333
