### ISSUE TITLE
功能提议：将方案列表改成二级菜单

### ISSUE THREAD

**Issue by laubonghaudoi** [jimmy54/iRime-Resouce#13]
目前点击“选择方案”后，即直接显示所有可选方案。考虑到以后可能会有越来越多方案供选择，希望能将此列表改为二级菜单显示，例如第一级显示明月拼音、五笔等内置方案，还有“音形方案”、“吴语拼音”、“闽语拼音”等集合，点进“吴语拼音”后，再显示各地方案可选。这样能够更方便用户找到自己想要的方案。

**Comment by uliloewi** [comment]
安裝時還是找不到南京拼音。怎麼回事？

**Comment by laubonghaudoi** [comment]
@uliloewi 我在这个[PR](https://github.com/jimmy54/iRime-Resource/pull/12#issuecomment-478377307)里提到了这个问题，貌似作者目前还没回复。

**Comment by jimmy54** [comment]
二级菜单，需要有一个分类。使用频率很低。

**Comment by laubonghaudoi** [comment]
> 二级菜单，需要有一个分类。使用频率很低。

是的，目前方案数量较少的情况下并没有需要使用二级菜单分类。主要是考虑到以后可能会增加大量方案（方言拼音会有20个以上的方案），加上目前也没有方案搜索功能（右上角的放大镜点击后提示侵权删除，没有启动搜索），方案的排序方式也较乱，想要找到一个方案会比较麻烦。因此改用二级菜单是个比较好的解决方案。

**Comment by jimmy54** [comment]
手动配置还是挺麻烦。下个版本添加了一下。按中文排序的功能。
