### ISSUE TITLE
找不到南京話拼音

### ISSUE THREAD

**Issue by uliloewi** [jimmy54/iRime-Resouce#16]
langjin@0.1已經在“iRime云方案”中。iOS下載iRime後依然看不到南京拼音，但同樣技術的潮州拼音能看到。怎麼回事？

**Comment by jimmy54** [comment]
还没更新，后面会不定时更新。

**Comment by laubonghaudoi** [comment]
@jimmy54 请问之后能否实现一个实时检测此仓库抓取方案的功能？如果像现在这样，依赖于软件本身的更新，那无法保证用户用到最新方案。希望能实现在每次打开“选择方案”列表时，iRime能自动检查此仓库并生成可用列表，点击后自动从此抓取方案。

**Comment by jimmy54** [comment]
有空会把这个功能做出来。
