### ISSUE TITLE
Substitute Cantonese (Jyutping) Schema

### ISSUE THREAD

**Issue by sgalal** [jimmy54/iRime-Resouce#23]
<span lang="zh-HK">粵拼方案需要更換。</span>

<span lang="zh-HK">原来的</span> <https://github.com/rime/rime-jyutping> <span lang="zh-HK">已暫停維護，應替換為</span> <https://github.com/rime/rime-cantonese><span lang="zh-HK">。</span>

**Comment by laubonghaudoi** [comment]
非常同意，不過換之前需要問一下作者兼容性的問題。是應該直接替換調rime-jyutping還是保留並另加rime-cantonese。如果沒有兼容性考慮的話，我們傾向於直接替換。

**Comment by jimmy54** [comment]
iRime是否试过能用？

**Comment by laubonghaudoi** [comment]
@jimmy54 請見下兩圖，聲調版與IPA版均可正常運作，聲調輸入也正常。
![107926310_105710](https://user-images.githubusercontent.com/11172180/79285042-368f8100-7e71-11ea-9c3e-7d946f9a8a5a.jpg)
![806528091_2564](https://user-images.githubusercontent.com/11172180/79285044-37281780-7e71-11ea-92fd-723e0573befe.jpg)

**Comment by laubonghaudoi** [comment]
剛纔的 https://github.com/jimmy54/iRime-Resource/pull/25 新增了 rime-cantonese 碼表並更新了原有的 rime-jyutping 碼表，如果 @jimmy54 覺得沒有兼容性問題的話，可以直接把 rime-jyutping 刪除，rime-cantonese 作爲唯一粵拼碼表，這是個最優的解決辦法
